# Generated by Django 2.2.3 on 2019-07-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMGsched', '0002_auto_20190711_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gcomments',
            old_name='Event',
            new_name='gEvent',
        ),
        migrations.RenameField(
            model_name='icomments',
            old_name='Event',
            new_name='iEvent',
        ),
    ]
